package com.rhesis.sdk.examples;

import com.rhesis.sdk.RhesisClient;
import com.rhesis.sdk.entities.Endpoint;
import com.rhesis.sdk.entities.Project;
import com.rhesis.sdk.enums.ConnectionType;

import java.util.Map;

public class CreateEndpointExample {
    public static void main(String[] args) {
        // Initialize the global client
        RhesisClient client = RhesisClient.builder()
                .apiKey(System.getenv("RHESIS_API_KEY"))
                .build();
        RhesisClient.setDefault(client);

        // Endpoints must be connected to a Project.
        // You can find a project by its name instead of fetching the list.
        Project project;
        try {
            project = client.projects().findByName("Example Project (Insurance Chatbot)");
        } catch (IllegalArgumentException e) {
            System.err.println(e.getMessage());
            System.exit(1);
            return;
        }

        System.out.println("Using Project ID: " + project.id());

        // Build the endpoint object
        Endpoint newEndpoint = new Endpoint(
            null, // id generated by server
            "My Example Endpoint",
            "A sample endpoint created via Java SDK",
            ConnectionType.REST,
            "https://api.example.com",
            project.id(),
            "POST",
            "/v1/chat",
            Map.of("Authorization", "Bearer {{ auth_token }}", "Content-Type", "application/json"), // requestHeaders
            null, // queryParams
            Map.of("message", "{{ input }}"), // requestMapping
            Map.of("output", "$.response.text"), // responseMapping
            "my-secret-token" // authToken
        );

        // Create the endpoint using the Active Record style!
        Endpoint created = newEndpoint.push();
        System.out.println("Created Endpoint ID: " + created.id());
    }
}
